name = "sharex-r2-cloudflare-workers"
account_id = "6b9f7e0e1478562986a4db3cf9fcfac3"
workers_dev = true
routes = [
	{pattern = "r2-sharex.chaika.me", custom_domain = true, zone_name = "chaika.me"},
]

compatibility_date = "2022-04-22"
main = "./dist/index.mjs"

[build]
command = "npm run build"

[[r2_buckets]]
bucket_name = "sharex-files"
preview_bucket_name = "sharex-files"
binding = "R2_BUCKET"


[vars]
# Change to the domain your Public Bucket is connected to.
CUSTOM_PUBLIC_BUCKET_DOMAIN = "share.chaika.me"
# Change to not let the worker serve files, only allowing traffic through the Public Bucket. Do not set if you have old links pointing to the worker.
ONLY_ALLOW_ACCESS_TO_PUBLIC_BUCKET = true 